### ISSUE TITLE
contact info once we have email set up

### ISSUE THREAD

**Issue by thedaniel** [ZeroFucks/zerofucks.de#3]
'email here for booking / info / etc' type thing.

**Comment by atmos** [comment]
Finally got google apps going. Waiting on configuration.

**Comment by thedaniel** [comment]
info@ has the full name 'Information Systems' which, while pretty hilarious, is confusing if tryna actually do business. I think maybe some reference to Zero Fucks in there would be good. Only an admin can change this I believe (I just logged in as info and tried but the fields weren't editable)
